-- -- SQLite
-- CREATE TABLE Products (
-- Id INTEGER PRIMARY KEY AUTOINCREMENT,
-- Code VARCHAR(5) NOT NULL UNIQUE,
-- Name VARCHAR(75) NOT NULL,
-- Price DECIMAL(10, 2) NOT NULL,
-- EntryDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- Brand VARCHAR(20) NOT NULL
-- );

-- CREATE TABLE Carts (
-- Id INTEGER PRIMARY KEY AUTOINCREMENT,
-- Email VARCHAR(100) NOT NULL UNIQUE
-- );

-- CREATE TABLE ProductCart(
-- IdCart INT NOT NULL REFERENCES Carts(Id),
-- IdProduct INT NOT NULL REFERENCES Products(Id),
-- Quantity INT NOT NULL,
-- PRIMARY KEY ( IdCART, IdProduct) 
-- );

-- CREATE TABLE Invoices(
-- Id INTEGER PRIMARY KEY AUTOINCREMENT,
-- InvoiceNumber VARCHAR(5) NOT NULL UNIQUE NOT NULL,
-- PurchaseDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
-- Email VARCHAR(25) NOT NULL,
-- Total DECIMAL(10,2) NOT NULL);


-- CREATE TABLE InvoiceDetail(
-- Id INTEGER PRIMARY KEY AUTOINCREMENT,
-- IdInvoice INT NOT NULL REFERENCES Invoices(Id),
-- IdProduct INT NOT NULL REFERENCES Products(Id),
-- TotalAmount DECIMAL(10,2) NOT NULL
-- );


-- ACA HAY UN TEMA QUE SE HABLO EN LA LECCION, AL AGREGAR UNA NUEVA TABLA CON NOT NULL,
-- SI NO LE DOY UN VALOR, NO DEJA AGREGAR LA COLUMNA, YA QUE EXISTEN TABLAS ANTERIORES,
-- QUE NO TENDRIAN UN VALOR, ENTONCES ESE VALOR SE LE AGREGA A ESAS QUE NO TENIAN ESE DATO

-- ALTER TABLE Invoices
-- ADD COLUMN PhoneNumber VARCHAR(15) NOT NULL DEFAULT 'N/A';

-- OTRO LIMITANTE ES QUE SOLO PUEDA AGREGAR UNA COLUMNA CON EL ALTER TABLE
-- ALTER TABLE Invoices
-- ADD COLUMN CodeEmployee VARCHAR(5) NOT NULL DEFAULT 'N/A';



PRAGMA foreign_keys;

