
-- CREATE TABLE Customers (
-- CustomerID INTEGER PRIMARY KEY AUTOINCREMENT,
-- Name VARCHAR (100) NOT NULL,
-- Email VARCHAR (30) NOT NULL
-- );

-- CREATE TABLE Authors(
-- AuthorID INTEGER PRIMARY KEY AUTOINCREMENT,
-- Name VARCHAR (100) NOT NULL
-- );

-- CREATE TABLE Books (
-- BookID INTEGER PRIMARY KEY AUTOINCREMENT,
-- Name VARCHAR(100) NOT NULL,
-- Author INT REFERENCES Authors(AuthorID)
-- );

-- CREATE TABLE Rents (
-- RentID INTEGER PRIMARY KEY AUTOINCREMENT,
-- BookID INT NOT NULL REFERENCES Books(BookID),
-- CustomerID INT NOT NULL REFERENCES Customers(CustomerID),
-- State VARCHAR(10) NOT NULL
-- );

